apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      tier: {{ .Values.labels.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        tier: {{ .Values.labels.tier }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}_{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
  replicas: {{ .Values.replicaCount }}
