apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
  namespace: default
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingress_class | quote }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations.target_type | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.annotations.listen_ports | quote }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.annotations.certificate_arn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.annotations.ssl_redirect | quote }}
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ .Values.ingress.annotations.load_balancer_attributes | quote }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.annotations.group_name | quote }}
spec:
  rules:
    - host: {{ .Values.ingress.host.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.service.port }}