apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
spec:
  selector:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}