# name: BuildApp

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'app/backend/**'
#       - 'app/frontend/**'

# jobs:
#   changes:
#     name: Detect changed folders
#     runs-on: ubuntu-latest
#     outputs:
#       backend: ${{ steps.filter.outputs.backend }}
#       frontend: ${{ steps.filter.outputs.frontend }}
#     steps:
#       - uses: actions/checkout@v5
#         name: Get Code
#       - name: Detect which folders changed
#         id: filter
#         uses: dorny/paths-filter@v3
#         with:
#           filters: |
#             backend:
#               - 'app/backend/**'
#             frontend:
#               - 'app/frontend/**'

#   build-backend:
#     name: Build backend image
#     needs: changes
#     if: needs.changes.outputs.backend == 'true'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v5
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: app/backend
#           push: true
#           tags: rushidevops/user_app:backend_v1.01

#   build-frontend:
#     name: Build frontend image
#     needs: changes
#     if: needs.changes.outputs.frontend == 'true'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v5

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: app/frontend
#           push: true
#           tags: rushidevops/user_app:frontend_v1.01


name: BuildApp

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'
      - 'app/frontend/**'
  workflow_dispatch:

jobs:
  changes:
    name: Detect changed folders
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        name: Get Code
      - name: Detect which folders changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'app/backend/**'
            frontend:
              - 'app/frontend/**'
      - name: Set version tag
        id: tag
        run: |
          TAG="v1.${{ github.run_number }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated tag: $TAG"

  build-backend:
    name: Build backend image
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/backend
          push: true
          tags: rushidevops/user_app:${{ needs.changes.outputs.tag }}

  build-frontend:
    name: Build frontend image
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/frontend
          push: true
          tags: rushidevops/user_app:${{ needs.changes.outputs.tag }}
