# name: BuildApp

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'app/backend/**'
#       - 'app/frontend/**'

# jobs:
#   changes:
#     name: Detect changed folders
#     runs-on: ubuntu-latest
#     outputs:
#       backend: ${{ steps.filter.outputs.backend }}
#       frontend: ${{ steps.filter.outputs.frontend }}
#     steps:
#       - uses: actions/checkout@v5
#         name: Get Code
#       - name: Detect which folders changed
#         id: filter
#         uses: dorny/paths-filter@v3
#         with:
#           filters: |
#             backend:
#               - 'app/backend/**'
#             frontend:
#               - 'app/frontend/**'

#   build-backend:
#     name: Build backend image
#     needs: changes
#     if: needs.changes.outputs.backend == 'true'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v5
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: app/backend
#           push: true
#           tags: rushidevops/user_app:backend_v1.01

#   build-frontend:
#     name: Build frontend image
#     needs: changes
#     if: needs.changes.outputs.frontend == 'true'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v5

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: app/frontend
#           push: true
#           tags: rushidevops/user_app:frontend_v1.01


name: BuildApp

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'
      - 'app/frontend/**'
  workflow_dispatch:

jobs:
  changes:
    name: Detect changed folders
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v5
        name: Get Code
      - name: Detect which folders changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'app/backend/**'
            frontend:
              - 'app/frontend/**'

  build-backend:
    name: Build backend image
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.NEW_TAG }}
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest backend version
        id: version
        run: |
          LATEST=$(curl -s https://hub.docker.com/v2/repositories/rushidevops/user_app/tags/?page_size=100 | jq -r '.results[].name' | grep backend_v | sort -V | tail -n 1)
          echo "Latest tag: $LATEST"
          if [ -z "$LATEST" ]; then
            NEW_TAG="backend_v1.01"
          else
            VERSION_NUM=$(echo $LATEST | sed 's/backend_v//' | awk '{printf "%.2f", $1 + 0.01}')
            NEW_TAG="backend_v${VERSION_NUM}"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $NEW_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/backend
          push: true
          tags: rushidevops/user_app:${{ steps.version.outputs.NEW_TAG }}

  build-frontend:
    name: Build frontend image
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.NEW_TAG }}
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest frontend version
        id: version
        run: |
          LATEST=$(curl -s https://hub.docker.com/v2/repositories/rushidevops/user_app/tags/?page_size=100 | jq -r '.results[].name' | grep frontend_v | sort -V | tail -n 1)
          echo "Latest tag: $LATEST"
          if [ -z "$LATEST" ]; then
            NEW_TAG="frontend_v1.01"
          else
            VERSION_NUM=$(echo $LATEST | sed 's/frontend_v//' | awk '{printf "%.2f", $1 + 0.01}')
            NEW_TAG="frontend_v${VERSION_NUM}"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $NEW_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/frontend
          push: true
          tags: rushidevops/user_app:${{ steps.version.outputs.NEW_TAG }}
