name: BuildBackendApp

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'
      - 'helm/backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    name: Detect changed folders
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      helm: ${{ steps.filter.outputs.helm }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        name: Get Code
      - name: Detect which folders changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'app/backend/**'
            helm:
              - 'helm/backend/**'
      - name: Set version tag
        id: tag
        run: |
          TAG="v1.${{ github.run_number }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated tag: $TAG"

  build-backend-image:
    name: Build backend image
    needs: changes
    if: needs.changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/backend
          push: true
          tags: rushidevops/user_app:backend_${{ needs.changes.outputs.tag }}

  deploy-same-image:
    name: Deploy same image
    needs: changes
    if: needs.changes.outputs.helm == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::086227530319:role/tf-role
          aws-region: us-east-1
          role-session-name: GitHubActions
      - name: Apply Helm Configurations
        run: helm upgrade --install user-app-backend helm/backend --reuse-values --atomic 

  deploy-new-image:
    name: Deploy New image
    needs: [changes, build-backend-image]
    if: needs.changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::086227530319:role/tf-role
          aws-region: us-east-1
          role-session-name: GitHubActions
      - name: Apply Helm Configurations
        run: helm upgrade --install user-app-backend helm/backend --set image.version=${{ needs.changes.outputs.tag }} --reuse-values --atomic 